### ISSUE TITLE
Package for mate-extra/mintmenu

### ISSUE THREAD

**Issue by FabioBeneditto** [rinaldus/rinaldus-overlay#10]
Hi!

Package 5.7.0 for mintmenu is not available: in Linuxmint repositories, actual version is 5.7.2.

May you update?

**Comment by rinaldus** [comment]
Updated. Thanks for your report!

**Comment by FabioBeneditto** [comment]
Another issue: language pack also was updated:

Version on server is http://packages.linuxmint.com/pool/main/m/mint-translations/mint-translations_2016.06.25.tar.xz

**Comment by rinaldus** [comment]
Sorry, I forgot about the translations yesterday. Thanks!

**Comment by FabioBeneditto** [comment]
My MR doesn't work fine :(

`Calculating dependencies | \* Digest verification failed:
- /var/lib/layman/rinaldus-overlay/mate-extra/mintmenu/mintmenu-5.7.2.ebuild
- Reason: Failed on SHA256 verification
- Got: f8ce47649d510e1a772d9cc308beefacf15beb3e2311084584b33a3aa83b9a87
- Expected: 42b3bb8ea1221d1c5fac44f58b86a44a52ed5bc721a9b0a026455046631feff8
  ... done!

> > > Verifying ebuild manifests

!!! Digest verification failed:
!!! /var/lib/layman/rinaldus-overlay/mate-extra/mintmenu/mintmenu-5.7.2.ebuild
!!! Reason: Failed on SHA256 verification
!!! Got: f8ce47649d510e1a772d9cc308beefacf15beb3e2311084584b33a3aa83b9a87
!!! Expected: 42b3bb8ea1221d1c5fac44f58b86a44a52ed5bc721a9b0a026455046631feff8
`

**Comment by rinaldus** [comment]
Remanifested. Please, check.
