### ISSUE TITLE
Mate-1.12.0

### ISSUE THREAD

**Issue by pupsik2115** [rinaldus/rinaldus-overlay#2]
Здравствуйте!

 При попытке обновиться выпадает куча конфликтов такого характера: !!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

x11-themes/mate-themes:0

  (x11-themes/mate-themes-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =x11-themes/mate-themes-1.12.0 (Argument)

  (x11-themes/mate-themes-1.8.0:0/0::gentoo, installed) pulled in by
    =x11-themes/mate-themes-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                       ^^^^                                                                                                                 

mate-base/mate-menus:0

  (mate-base/mate-menus-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    >=mate-base/mate-menus-1.9:0 required by (mate-extra/mate-screensaver-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
    ^^                     ^^^^^  
    =mate-base/mate-menus-1.12.0 (Argument)

  (mate-base/mate-menus-1.8.0:0/0::gentoo, installed) pulled in by
    =mate-base/mate-menus-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                     ^^^^                                                                                                                 

mate-extra/mate-power-manager:0

  (mate-extra/mate-power-manager-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-extra/mate-power-manager-1.12.0 (Argument)

  (mate-extra/mate-power-manager-1.8.0-r1:0/0::gentoo, installed) pulled in by
    =mate-extra/mate-power-manager-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                              ^^^^                                                                                                                 

mate-base/mate-panel:0

  (mate-base/mate-panel-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    >=mate-base/mate-panel-1.8:0[gtk3?] required by (mate-extra/mate-utils-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                 ^^^^^  
    >=mate-base/mate-panel-1.8:0[gtk3?] required by (mate-extra/mate-sensors-applet-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                 ^^^^^  
    >=mate-base/mate-panel-1.8:0[gtk3?] required by (net-analyzer/mate-netspeed-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                 ^^^^^  
    >=mate-base/mate-panel-1.8:0[gtk3?] required by (mate-extra/mate-media-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                 ^^^^^  
    >=mate-base/mate-panel-1.8:0[gtk3?] required by (mate-base/mate-applets-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                 ^^^^^  
    =mate-base/mate-panel-1.12.0 (Argument)

  (mate-base/mate-panel-1.8.0:0/0::gentoo, installed) pulled in by
    =mate-base/mate-panel-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                     ^^^^                                                                                                                 

x11-terms/mate-terminal:0

  (x11-terms/mate-terminal-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =x11-terms/mate-terminal-1.12.0 (Argument)

  (x11-terms/mate-terminal-1.8.0:0/0::gentoo, installed) pulled in by
    =x11-terms/mate-terminal-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                        ^^^^                                                                                                                 

mate-base/mate-session-manager:0

  (mate-base/mate-session-manager-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-base/mate-session-manager-1.12.0 (Argument)

  (mate-base/mate-session-manager-1.8.1-r1:0/0::gentoo, installed) pulled in by
    =mate-base/mate-session-manager-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                               ^^^^                                                                                                                 

mate-extra/mate-media:0

  (mate-extra/mate-media-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-extra/mate-media-1.12.0 (Argument)

  (mate-extra/mate-media-1.8.0:0/0::gentoo, installed) pulled in by
    =mate-extra/mate-media-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                      ^^^^                                                                                                                 

mate-extra/mate-screensaver:0

  (mate-extra/mate-screensaver-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-extra/mate-screensaver-1.12.0 (Argument)

  (mate-extra/mate-screensaver-1.8.0:0/0::gentoo, installed) pulled in by
    =mate-extra/mate-screensaver-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                            ^^^^                                                                                                                 

mate-extra/mate-system-monitor:0

  (mate-extra/mate-system-monitor-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-extra/mate-system-monitor-1.12.0 (Argument)

  (mate-extra/mate-system-monitor-1.8.0:0/0::gentoo, installed) pulled in by
    =mate-extra/mate-system-monitor-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                               ^^^^                                                                                                                 

mate-base/mate-desktop:0

  (mate-base/mate-desktop-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    >=mate-base/mate-desktop-1.6:0[gtk3?] required by (mate-base/mate-applets-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                   ^^^^^  
    >=mate-base/mate-desktop-1.10:0[gtk3?] required by (x11-terms/mate-terminal-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
    ^^                       ^^^^^^  
    =mate-base/mate-desktop-1.12.0 (Argument)
    (and 7 more with the same problems)

  (mate-base/mate-desktop-1.8.1-r1:0/0::gentoo, installed) pulled in by
    =mate-base/mate-desktop-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                       ^^^^                                                                                                                 

mate-base/mate-applets:0

  (mate-base/mate-applets-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-base/mate-applets-1.12.0 (Argument)

  (mate-base/mate-applets-1.8.0-r1:0/0::gentoo, installed) pulled in by
    =mate-base/mate-applets-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                       ^^^^                                                                                                                 

mate-extra/mate-utils:0

  (mate-extra/mate-utils-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-extra/mate-utils-1.12.0 (Argument)

  (mate-extra/mate-utils-1.8.0:0/0::gentoo, installed) pulled in by
    =mate-extra/mate-utils-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                      ^^^^                                                                                                                 

x11-themes/mate-icon-theme:0

  (x11-themes/mate-icon-theme-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =x11-themes/mate-icon-theme-1.12.0 (Argument)
    >=x11-themes/mate-icon-theme-1.9:0 required by (mate-extra/mate-system-monitor-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
    ^^                           ^^^^^                                                                                                                                                                                

  (x11-themes/mate-icon-theme-1.8.0:0/0::gentoo, installed) pulled in by
    =x11-themes/mate-icon-theme-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                           ^^^^                                                                                                                 

x11-wm/marco:0

  (x11-wm/marco-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    >=x11-wm/marco-1.8.2:0 required by (mate-base/mate-control-center-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
    ^^             ^^^^^^^                                                                                                                                                                               

  (x11-wm/marco-1.8.0:0/0::gentoo, installed) pulled in by
    =x11-wm/marco-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^             ^^^^                                                                                                                 

mate-base/caja:0

  (mate-base/caja-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    >=mate-base/caja-1.8:0[gtk3?] required by (mate-extra/mate-user-share-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                           ^^^^^  
    >=mate-base/caja-1.8:0[gtk3?] required by (mate-base/mate-control-center-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                           ^^^^^                                                                                                                                          

  (mate-base/caja-1.8.1:0/0::gentoo, installed) pulled in by
    =mate-base/caja-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^               ^^^^                                                                                                                 

mate-base/mate-settings-daemon:0

  (mate-base/mate-settings-daemon-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    >=mate-base/mate-settings-daemon-1.6:0[gtk3?] required by (mate-base/mate-control-center-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                           ^^^^^  
    >=mate-base/mate-settings-daemon-1.6:0[gtk3?] required by (mate-base/mate-applets-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge)
                                           ^^^^^  
    =mate-base/mate-settings-daemon-1.12.0 (Argument)

  (mate-base/mate-settings-daemon-1.8.1:0/0::gentoo, installed) pulled in by
    =mate-base/mate-settings-daemon-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                               ^^^^                                                                                                                 

mate-base/mate-control-center:0

  (mate-base/mate-control-center-1.12.0:0/0::rinaldus-overlay, ebuild scheduled for merge) pulled in by
    =mate-base/mate-control-center-1.12.0 (Argument)

  (mate-base/mate-control-center-1.8.1:0/0::gentoo, installed) pulled in by
    =mate-base/mate-control-center-1.8\* required by (mate-base/mate-1.8.0:0/0::gentoo, installed)
    ^                              ^^^^                            

К тому же не хватает eom-1.12.0, так как этот пакет в зависимостях в mate-base/mate-1.12.0. Исправьте пожалуйста.

**Comment by rinaldus** [comment]
По поводу конфликтов, попробуйте предварительно удалить MATE 1.8 со всеми его зависимостями. Затем сделайте emerge mate-base/mate. Должен притянуться MATE 1.12 из моего оверлея.
По поводу eom-1.12.0 я и в самом деле забыл его добавить. Спасибо, что напомнили. :) Уже добавил.
Тему закрывать пока не буду, но Вы, пожалуйста, отпишитесь здесь о результатах, получилось разрешить конфликты и установить версию 1.12?

**Comment by pupsik2115** [comment]
Сделал, как вы сказали. Всё собралось. Но обновлением это явно не назовёшь.
