### ISSUE TITLE
Some MATE components were updated

### ISSUE THREAD

**Issue by SmoothDude** [rinaldus/rinaldus-overlay#3]
Some packages in MATE have been updated (but not all). So versions should be increased in ebuilds as well.

**Comment by rinaldus** [comment]
Thank you for your report! These packages are bumped. Please check, if everything is correct.

**Comment by SmoothDude** [comment]
Built fine, but with several QA notices (some of them related to ebuilds, part of elog attached to the post)
[elog.txt](https://github.com/rinaldus/rinaldus-overlay/files/56752/elog.txt)

Haven't found any problems in packages itself, I'll let you know if something is going wrong due ebuilds
