### ISSUE TITLE
DeaDBeeF requires jansson

### ISSUE THREAD

**Issue by SmoothDude** [rinaldus/rinaldus-overlay#4]
It requires this library in order to build successfully: dev-libs/jansson
Also attached some QA Notices thrown after emerging.
[notices.txt](https://github.com/rinaldus/rinaldus-overlay/files/56822/notices.txt)

Attempted to build package with following use flags: aac, alac, alsa, ape, cdda, curl, dts, ffmpeg, flac, gtk2, m3u, midi, mp3, nls, notify, nullout, threads, vorbis, wma.

**Comment by rinaldus** [comment]
Please, send your build.log

**Comment by rinaldus** [comment]
I fixed the ebuild. Please, check it.
