### ISSUE TITLE
=mate-base/mate-desktop-1.13.0 installation fails

### ISSUE THREAD

**Issue by SmoothDude** [rinaldus/rinaldus-overlay#6]
It can be fixed by removing 68th line from ebuild:
python_replicate_script "${ED}"/usr/bin/mate-conf-import

MATE devs removed this script in this commit: https://github.com/mate-desktop/mate-desktop/commit/fa02f5274b660b73e21b14d14b06f4dddcdf9512

**Comment by rinaldus** [comment]
Fixed. Please, check installation. I can't check it myself right now.

**Comment by SmoothDude** [comment]
Yeah, it works

**Comment by rinaldus** [comment]
Thank you for your help!
