### ISSUE TITLE
>=mate-system-monitor-1.13.0 dropped GTK+2 support

### ISSUE THREAD

**Issue by SmoothDude** [rinaldus/rinaldus-overlay#7]
And due this build with GTK+2 support fails. Here are 3 options:
- Follow this change and remove GTK+2 support from ebuild as well
- Adopt new changes from 1.13.0 in a form of patch to GTK+2 version
- Temporary remove mate-system-monitor-1.13.0

**Comment by rinaldus** [comment]
I removed GTK 2 support and made GTK 3 support as default. It works in my computer now. Please, check.
