### ISSUE TITLE
File size mismatch

### ISSUE THREAD

**Issue by lexa500** [rinaldus/rinaldus-overlay#8]
> > > Downloading 'https://github.com/haiwen/ccnet/archive/v5.0.6.tar.gz'
> > > --2016-03-21 00:54:38--  https://github.com/haiwen/ccnet/archive/v5.0.6.tar.gz
> > > Resolving github.com... 192.30.252.128
> > > Connecting to github.com|192.30.252.128|:443... connected.
> > > HTTP request sent, awaiting response... 302 Found
> > > Location: https://codeload.github.com/haiwen/ccnet/tar.gz/v5.0.6 [following]
> > > --2016-03-21 00:54:39--  https://codeload.github.com/haiwen/ccnet/tar.gz/v5.0.6
> > > Resolving codeload.github.com... 192.30.252.162
> > > Connecting to codeload.github.com|192.30.252.162|:443... connected.
> > > HTTP request sent, awaiting response... 200 OK
> > > Length: 221835 (217K) [application/x-gzip]
> > > Saving to: ‘/usr/portage/distfiles/ccnet-5.0.6.tar.gz’

/usr/portage/distfi 100%[===================>] 216,64K   465KB/s    in 0,5s    

2016-03-21 00:54:40 (465 KB/s) - ‘/usr/portage/distfiles/ccnet-5.0.6.tar.gz’ saved [221835/221835]

!!! Fetched file: ccnet-5.0.6.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      221835
!!! Expected: 221823
Refetching... File renamed to '/usr/portage/distfiles/ccnet-5.0.6.tar.gz._checksum_failure_.gTU9Rk'

!!! Couldn't download 'ccnet-5.0.6.tar.gz'. Aborting.
- Fetch failed for 'net-libs/ccnet-5.0.6', Log file:
-  '/var/tmp/portage/net-libs/ccnet-5.0.6/temp/build.log'

> > > Failed to emerge net-libs/ccnet-5.0.6, Log file:
> > > 
> > >  '/var/tmp/portage/net-libs/ccnet-5.0.6/temp/build.log

**Comment by rinaldus** [comment]
Fixed. Please, check.

**Comment by lexa500** [comment]
works fine. thanks!
